# File: .github/workflows/deploy.yml

on:
    workflow_dispatch:

name: AzureLoginSample

env:
   TargetEnvironment: prod
   registryName: hjkltdevopsreg
   repositoryName: wth-team7/dotnetcoreapp
   dockerFolderPath: Application/src/RazorPagesTestSample
   tag: ${{github.run_number}}
   
   

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTIONID}}
        resourceGroupName: ${{ vars.RG}}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=hjklt-devops-${{env.TargetEnvironment}}
        
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      run: docker login ${{env.registryName}} -u ${{ secrets.ACR_USERNAME}} -p ${{ secrets.ACR_PASSWORD}}
      
    - name: Docker Build
      run: docker build -t ${{env.registryName}}/${{env.registryName}}:${{env.tag}} --build-arg build_version=${{env.tag}} ${{env.dockerFolderPath}}
      
    - name: Docker Push
      run: docker push ${{env.registryName}}/${{env.registryName}}:${{env.tag}}
